name: Deploy static content to Pages

on:
  push:
    branches: ["main", "gh-pages"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy PR to subdirectory
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          pr_number=${{ github.event.pull_request.number }}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Configure git to use the GITHUB_TOKEN for authentication
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git

          # Fetch and checkout with better error handling
          git fetch origin gh-pages || echo "No gh-pages branch yet"
          git checkout gh-pages || git checkout -b gh-pages

          # Create directory and clean it if it exists
          mkdir -p "pr-${pr_number}"
          rm -rf "pr-${pr_number:?}"/* || echo "Directory was empty"

          # Copy content
          rsync -av --exclude=".git" --exclude="pr-${pr_number}" ./ "pr-${pr_number}/"

          # Commit and push
          git add "pr-${pr_number}"
          git commit -m "Update PR #${pr_number}" || echo "No changes to commit"
          git push origin gh-pages

          # Add a comment to the pull request with the URL
          pr_url="https://${{ github.repository_owner }}.github.io/${{ github.repository }}/pr-${pr_number}"
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            -d "{\"body\": \"Preview URL: ${pr_url}\"}"
