name: Check PR Bot Comment and Last Action

on:
  issue_comment:
    types: [created]

jobs:
  check-bot-comment-and-status:
    if: |
      github.event.comment.user.login == 'github-actions[bot]' &&
      contains(github.event.comment.body, 'Update PR #')
    runs-on: ubuntu-latest
    steps:
      - name: Check last main.yml workflow run status for PR
        uses: actions/github-script@v6
        with:
          script: |
            const core = require('@actions/core');
            const prNumber = context.payload.issue.number;
            const { data: workflows } = await github.rest.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const mainWorkflow = workflows.workflows.find(wf => wf.name === 'Sync Main to GitHub Pages with PR Previews');
            if (!mainWorkflow) {
              core.setFailed('main.yml workflow not found.');
              return;
            }
            const { data: runs } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: mainWorkflow.id,
              event: 'pull_request',
              per_page: 10
            });
            // Find the latest run for this PR
            const run = runs.workflow_runs.find(r => r.pull_requests.some(pr => pr.number === prNumber));
            if (!run) {
              core.setFailed('No main.yml workflow run found for this PR.');
            } else if (run.conclusion === 'success') {
              console.log('Last main.yml workflow run succeeded.');
            } else {
              core.setFailed('Last main.yml workflow run did not succeed.');
            }
